version: '3.8'
services:
  app:
    build:
      context: ./client  # Assurez-vous que ce chemin mène au dossier contenant le Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Expose le port 5000 pour accéder à l'application depuis le navigateur
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
