version: '3.8'
services:
  app:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - mongo
    environment:
      ATLAS_URI: mongodb://mongo:27017/vacationdb
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/usr/src/app/src
  mongo:
    image: mongo
    ports:
      - "27017:27017"
