version: '3.8'
services:
  app:
    build: ./server # Assurez-vous que le Dockerfile est dans ce répertoire
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=mysecret

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: vacationdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
